name: nlp-phobert-feedback
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - pip:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - jupyter
      - datasets
      - transformers
      - torch
      - pyyaml
      - tqdm
      - joblib
